version: '3.8'

services:
  php-fpm:
    build: .docker/php
    container_name: "builder-pattern-php"
    entrypoint: .docker/entrypoint.sh
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
      - ENVIRONMENT=local
    volumes:
      - .:/var/www
    networks:
      - builder-pattern-network
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    build: .docker/nginx
    container_name: "builder-pattern-nginx"
    restart: always
    tty: true
    ports:
      - "8482:80"
    volumes:
      - .:/var/www
    networks:
      - builder-pattern-network
    depends_on:
      - php-fpm

networks:
  builder-pattern-network:
    driver: bridge
